data:
  raw_path: data/raw/
  processed_path: data/processed/
  delta_path: data/delta/

mlflow:
  experiment_name: home_credit_default
  tracking_uri: mlruns/

model:
  output_path: models/

app:
  streamlit_app: app/streamlit_app.py

